### ISSUE TITLE
Error covert to BN

### ISSUE THREAD

**Issue by cauta** [chainstacklabs/evm-blockchain-bridge#5]
https://github.com/chainstacklabs/evm-blockchain-bridge/blame/9f5e7e7aed33f300b5659ac35f98f62a0b4c1c87/backend/contract-methods.js#L70

this line increase gas to a floating point number that leads to error convert gas value

**Comment by soos3d** [comment]
Hi @cauta , let me look into it!

**Comment by soos3d** [comment]
Hi @cauta.

You are indeed correct. I pushed a change to fix that; thanks for the heads up! Now it's like this:

```js
gas: Math.ceil(gas * 1.2),
```

- [Fix](https://github.com/chainstacklabs/evm-blockchain-bridge/blob/bb4eea6c4887f3c688984c13f1ca461aadfb5ec8/backend/contract-methods.js#L70)

Which keeps the value as an integer. Please note that this is not a very good practice, and it's there just to make sure the transaction goes through by manually adding 20%. The gas is calculated on this [line](https://github.com/chainstacklabs/evm-blockchain-bridge/blob/bb4eea6c4887f3c688984c13f1ca461aadfb5ec8/backend/contract-methods.js#L52).

**Comment by cauta** [comment]
> Hi @cauta.
> 
> You are indeed correct. I pushed a change to fix that; thanks for the heads up! Now it's like this:
> 
> ```js
> gas: Math.ceil(gas * 1.2),
> ```
> 
>  * [Fix](https://github.com/chainstacklabs/evm-blockchain-bridge/blob/bb4eea6c4887f3c688984c13f1ca461aadfb5ec8/backend/contract-methods.js#L70)
> 
> Which keeps the value as an integer. Please note that this is not a very good practice, and it's there just to make sure the transaction goes through by manually adding 20%. The gas is calculated on this [line](https://github.com/chainstacklabs/evm-blockchain-bridge/blob/bb4eea6c4887f3c688984c13f1ca461aadfb5ec8/backend/contract-methods.js#L52).

Thanks @soos3d , i understand the context.
